# -*- coding: UTF-8 -*-

# NOTE: 表格中必须要有的key
REQUIRED_KEY_YEAR = u'年'
REQUIRED_KEY_WEEK = u'周'

REQUIRED_KEY_CATEGORY = u'品牌'
REQUIRED_KEY_MODEL = u'型号'
REQUIRED_KEY_PRODECT_TYPE = u'产品类型'
REQUIRED_KEY_IS_MUTI_DOOR = u'多门十字'

REQUIRED_KEY_SELL_COUNT = u'零售量'
REQUIRED_KEY_SINGLE_PRICE = u'单价'

REQUIRED_KEY_REGION = u'城市'

REQUIRED_KEYS = [
	REQUIRED_KEY_YEAR,
	REQUIRED_KEY_WEEK,

	REQUIRED_KEY_CATEGORY,
	REQUIRED_KEY_MODEL,
	REQUIRED_KEY_PRODECT_TYPE,
	REQUIRED_KEY_IS_MUTI_DOOR,

	REQUIRED_KEY_SELL_COUNT,
	REQUIRED_KEY_SINGLE_PRICE,

	REQUIRED_KEY_REGION,
]

# NOTE: 后处理的一些key
POST_KEY_SALES = 'post_key_sales'
POST_KEY_NAME = 'post_key_name'
POST_KEY_TIME_DUR = 'post_key_time_dur' # 时间段，年份+月份
POST_KEY_MERGE_RABLE_IDS = 'post_key_merge_table_ids' # 融合了哪些行
POST_KEY_NEW_TYPE = 'post_key_new_type' # 处理之后的类型

# NOTE: 价位分段
PRICE_SEGMENT = [
	30000,
	20000,
	15000,
	10000,
	8000,
	6000,
	5500,
	5000,
	4500,
	4000,
	3500,
	3000,
	2500,
	2000,
]

# NOTE: 分类的key
CATEGORY_KEYS = [REQUIRED_KEY_CATEGORY, POST_KEY_NEW_TYPE]
